Update the script fix for gemma-3-4b test  (#225)
Fixing the test model file name to gemma-3-4b-it.yaml and also upload
the model file.

Test is failing at
https://github.com/vllm-project/vllm-gaudi/actions/runs/17926460012/job/50985856988?pr=150
due to missing file after
https://github.com/vllm-project/vllm-gaudi/pull/150.
```
Testing gemma-3-4b-it
VLLM_SKIP_WARMUP=true PT_HPU_LAZY_MODE=1 VLLM_USE_V1=1 python -u vllm-gaudi/tests/models/language/generation/generation_mm.py --model-card-path vllm-gaudi/tests/full_tests/model_cards/gemma-3-27b-it.yaml
...
FileNotFoundError: [Errno 2] No such file or directory: 'vllm-gaudi/tests/full_tests/model_cards/gemma-3-27b-it.yaml'
```

---------

Signed-off-by: Jimin Ha <jimin.ha@intel.com>