Revert "Set device according to local rank" (#946)
Reverts vllm-project/vllm-gaudi#788
Due to next issue:
RuntimeError: Invalid HABANA_VISIBLE_MODULES=5. Module IDs should be
between 0 and 0.

Co-authored-by: Jakub Byczkowski <jbyczkowski@habana.ai>