Fix INC patching _gate twice (#955)
It failed with: "return torch.nn.functional.linear(x, weight, bias)
RuntimeError: matrix 1 and matrix 2 shapes cannot be multiplied" because
after the PR: https://github.com/vllm-project/vllm/pull/26440/changes
the FusedMoe uses _gate which causes us when we generate model info in
INC to overwrite _gate info:

First as mlp.gate → dict maps gate_obj → (parent=mlp, name="gate")
Then as mlp.experts._gate → dict maps gate_obj → (parent=experts,
name="_gate")

and then when the NIC runs it makes two objects where one can handle fp8
correctly while the second doesn't. Hiding the _gate inside the FusedMoe
makes it create the correct object and after that we can set _gate
inside fusedmoe back.

I think in the fork we used "def _remove_duplicate_submodules(self):" to
remove duplicates because of similar issue.

---------

Signed-off-by: Kamil Kaczor <kamil.kaczor@intel.com>