[FIX_FOR_VLLM_LATEST] Quick fix for PR30684 (#742)
1) Quick fix for upstream changes:
[PR30684](https://github.com/vllm-project/vllm/pull/30684)
2) Fix for upstream changes:
https://github.com/vllm-project/vllm/pull/28891 (Port:
[PR751](https://github.com/vllm-project/vllm-gaudi/pull/751))
3) Fix for https://github.com/vllm-project/vllm/pull/31036
issue: failed test case run_qwen3_compressed_tensor_dynamic_scaling_test
```(EngineCore_DP0 pid=5792)   File "/root/logs/vllm/vllm/model_executor/layers/fused_moe/layer.py", line 1487, in ensure_moe_quant_config_init
(EngineCore_DP0 pid=5792)     self.quant_method.get_fused_moe_quant_config(self)
(EngineCore_DP0 pid=5792)   File "/root/logs/vllm/vllm/model_executor/layers/quantization/fp8.py", line 1225, in get_fused_moe_quant_config
(EngineCore_DP0 pid=5792)     w1_scale=layer.w13_weight_scale,
(EngineCore_DP0 pid=5792)              ^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=5792)   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1964, in __getattr__
(EngineCore_DP0 pid=5792)     raise AttributeError(
(EngineCore_DP0 pid=5792) AttributeError: 'FusedMoE' object has no attribute 'w13_weight_scale'. Did you mean: 'w13_weight_scale_inv'```

This issue was already present, but it was not detected as marlin was disabled. After moe refactor in https://github.com/vllm-project/vllm/pull/31036, parameter self.use_marlin was replaced by self.fp8_backend. self.fp8_backend is disabled now

---------

Signed-off-by: Iryna Boiko <iboiko@habana.ai>