add torch inference decorator back to warmup (#1104)
Torch inference decorator mistakenly removed from #1054, adding it back
as it was causing below issue


```
AssertionError: Optimized softmax mode is supported in recompute training mode only in causal(triangular) mask case
```

Signed-off-by: Shiv Kaul <shiv.kaul@intel.com>